import { expect, test } from "@playwright/test";

test("account home, independent windows, account-bound requests and cross-account paste rejection", async ({ page }) => {
  await page.setViewportSize({ width: 1500, height: 1000 });
  await page.addInitScript(() => Object.defineProperty(navigator, "languages", { get: () => ["zh-CN"] }));
  const accounts = ["1", "2"].map((id) => ({ accountId: id, name: `账号${id}`, avatar: "", usedBytes: 1024, totalBytes: 2048 }));
  const requests: { method: string; params: Record<string, unknown> }[] = [];
  const errors: string[] = []; page.on("pageerror", (e) => errors.push(e.message));
  await page.route("**/api/**", async (route) => {
    const path = new URL(route.request().url()).pathname;
    let data: unknown = [];
    if (path === "/api/init/status") data = { needsInitialization: false };
    else if (path === "/api/auth/me") data = { id: 1, username: "admin" };
    else if (path === "/api/roots") data = [{ id: "a", name: "根目录A" }, { id: "b", name: "根目录B" }];
    else if (path === "/api/jobs/events") return route.fulfill({ contentType: "text/event-stream", body: 'event: jobs.snapshot\ndata: {"runtimeId":"accounts","cursor":0,"reset":false,"jobs":[]}\n\n' });
    else if (path.startsWith("/api/cloud115/")) {
      const method = path.split("/").at(-1)!; const params = route.request().postDataJSON(); requests.push({ method, params });
      if (method === "accounts") data = accounts;
      else if (method === "login.start") data = { image: "data:image/svg+xml;base64,PHN2Zy8+", loginSession: "test-add-account-session" };
      else if (method === "login.check") data = { loggedIn: false, status: 0 };
      else if (method === "status") data = { loggedIn: true };
      else if (method === "profile") data = accounts.find((a) => a.accountId === params.accountId);
      else if (method === "browse") data = { entries: [{ id: "1", name: "same.txt", parentId: "0", isDirectory: false, size: 1 }], offset: 0, total: 1 };
    }
    await route.fulfill({ json: { data } });
  });
  await page.goto("/");
  await page.getByRole("button", { name: "打开文件管理器", exact: true }).click();
  const local = page.locator('.desktop-window[data-window-kind="file"]');
  const localCard = local.getByRole("button", { name: /根目录A/ });
  await expect(localCard).toBeVisible();
  const icon = page.getByRole("button", { name: "打开115网盘", exact: true });
  await icon.click();
  const windows = page.locator('.desktop-window[data-window-kind="cloud115"]');
  const first = windows.nth(0);
  await expect(first.getByTestId("cloud-accounts")).toBeVisible();
  for (const button of await first.getByRole("navigation", { name: "文件操作" }).getByRole("button").all()) await expect(button).toBeDisabled();
  const localSize = (await localCard.boundingBox())!;
  const cloudSize = (await first.getByRole("button", { name: /^账号1/ }).boundingBox())!;
  expect(cloudSize.height).toBe(localSize.height);
  expect(cloudSize.width).toBeCloseTo(localSize.width, 0);
  const banner = first.locator('.virtual-root > header');
  expect((await banner.boundingBox())!.width).toBe((await first.locator('.virtual-root').boundingBox())!.width);
  await expect(first.getByRole("progressbar", { name: "账号1空间占用" })).toHaveAttribute("aria-valuenow", "50");
  const add = first.getByRole("button", { name: "添加新账号" });
  expect(await add.evaluate((element) => getComputedStyle(element).display)).toBe("flex");
  expect(await add.evaluate((element) => getComputedStyle(element).flexDirection)).toBe("row");
  expect(await add.evaluate((element) => element === element.parentElement!.lastElementChild)).toBe(true);
  await first.getByRole("button", { name: /^账号1/ }).click();
  await expect(first.getByTestId("cloud-accounts")).toBeVisible();
  await first.getByRole("button", { name: /^账号1/ }).dblclick();
  await expect(first.getByRole("button", { name: "same.txt", exact: true })).toBeVisible();
  await first.getByRole("button", { name: "same.txt", exact: true }).click();
  await page.keyboard.press("Control+c");
  await icon.click();
  const second = windows.nth(1);
  await expect(second.getByTestId("cloud-accounts")).toBeVisible();
  await second.getByRole("button", { name: /^账号2/ }).dblclick();
  await expect(second.getByRole("button", { name: "same.txt", exact: true })).toBeVisible();
  await expect(second.getByRole("button", { name: "账号列表", exact: true })).toHaveCount(0);
  await page.keyboard.press("Control+v");
  await expect(second.getByRole("dialog")).toHaveCount(0);
  await second.getByRole("button", { name: "same.txt", exact: true }).click({ button: "right" });
  await expect(page.getByRole("menuitem", { name: "粘贴", exact: true })).toHaveAttribute("aria-disabled", "true");
  await page.keyboard.press("Escape");
  expect(requests.filter((r) => r.method.startsWith("ops."))).toHaveLength(0);
  expect(requests.filter((r) => r.method === "browse").map((r) => r.params.accountId)).toEqual(["1", "2"]);
  await page.evaluate(() => window.dispatchEvent(new CustomEvent("cloud115-account-changed", { detail: { accountId: "1" } })));
  await expect(first.getByTestId("cloud-accounts")).toBeVisible();
  await expect(second.getByRole("button", { name: "same.txt", exact: true })).toBeVisible();
  await second.getByRole("button", { name: "切换115账号" }).click();
  await page.getByRole("menuitem", { name: "账号1", exact: true }).click();
  await expect(second.getByRole("button", { name: "切换115账号" })).toHaveText(/账号1/);
  await expect.poll(() => requests.filter((r) => r.method === "browse").at(-1)?.params.accountId).toBe("1");
  await second.getByRole("button", { name: "切换115账号" }).click();
  await page.getByRole("menuitem", { name: "添加新账号" }).click();
  await expect(second.getByRole("dialog", { name: "添加115账号" })).toBeVisible();
  await second.getByRole("button", { name: "取消", exact: true }).click();
  await expect(second.getByRole("button", { name: "切换115账号" })).toHaveText(/账号1/);
  expect(errors).toEqual([]);
  await page.screenshot({ path: "/tmp/filebutler-multi-account-windows.png" });
});
